Repository Bankar-Swapnil/PsychoMetricaX, pull requests merged in 2024-02, with the labels that each got.

#14 Update questionpaper.html
  templates/questionpaper.html
Labels: bug, good first issue

#15 Update selectquestionpaper.html
  templates/selectquestionpaper.html
Labels: bug, enhancement, good first issue

#16 new changes
  app.py
  cv/VAISHNAVI_PATTEWAR_RESUME_5.pdf
  templates/adminsettings.html
Labels: bug, enhancement, good first issue

#17 new changes
  templates/adminaddinstructor.html
Labels: bug, enhancement, good first issue

#19 new
  templates/adminaddinstructor.html
Labels: bug

#21 Update selectquestionpaper.html
  templates/selectquestionpaper.html
Labels: bug, enhancement, good first issue

#24 new updates
  app.py
  templates/profile.html
Labels: bug, enhancement

#26 apti
  templates/questionselect.html
  templates/questionviewselect.html
  templates/questionweightage.html
  templates/questionweightageadd.html
  templates/reportgeneration.html
Labels: bug, documentation, good first issue

#27 forget to commit
  templates/addquestion.html
  templates/adminaddinstructor.html
  templates/admineditstudent.html
  templates/quiz.html
Labels: bug, enhancement

#28 Update startquiz.html
  templates/startquiz.html
Labels: enhancement

#29 home_updates
  app.py
  templates/adminhome.html
  templates/instructorhome.html
Labels: enhancement
